name: CD

on:
  workflow_call:

jobs:
  cd-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Main branch step
        run: echo "Deploying MAIN"

  cd-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Staging branch step
        run: echo "Deploying STAGING"
